#soal 3
print("========== CATATAN BELANJA ==========")
print("========== Daftar 1 ==========")
print("Daftar Belanja 1: ['Sikat Gigi', 'Odol', 'Shampoo', 'Sabun', 'Ciduk']")
print("")
print("========== Daftar 2 ==========")
print("Daftar Belanja 1: ['Teh', 'Gula', 'Garam', 'Micin', 'Kecap']")
print("")
print("Jawab dengan angka [1/2]")
print("1. Rubah Belanjaan")
print("2. Keluar")
int(input("Masukan pilihan: "))
input("Masukan nama item ke daftar 1: ")
int(input("Masukan index yang ingin dirubah: "))
input("Masukan nama item ke daftar 2: ")
int(input("Masukan index yang ingin dirubah: "))
